
import { NodeCategory, CamaraAPI } from '../types/flow.types';

export const COLORS = {
  trigger: '#a3a3a3',
  telecom_signal: '#d4d4d8',
  condition: '#f59e0b',
  decision: {
    ALLOW: '#e4e4e7',
    VERIFY: '#f59e0b',
    BLOCK: '#ef4444',
  },
  bg: '#030303',
  surface: '#0b0b0f',
  border: 'rgba(255, 255, 255, 0.12)',
};

export const NODE_DEFINITIONS = [
  {
    type: 'trigger',
    label: 'Transaction Initiated',
    category: 'trigger' as NodeCategory,
    description: 'Real-time entry point for transaction requests.',
    icon: 'Zap',
  },
  {
    type: 'sim_swap',
    label: 'SIM Swap Detection',
    category: 'telecom_signal' as NodeCategory,
    camaraApi: 'sim_swap' as CamaraAPI,
    description: 'Check if the SIM card was recently replaced.',
    icon: 'Shield',
  },
  {
    type: 'device_status',
    label: 'Device Verification',
    category: 'telecom_signal' as NodeCategory,
    camaraApi: 'device_status' as CamaraAPI,
    description: 'Verify if the device is currently reported lost or stolen.',
    icon: 'Smartphone',
  },
  {
    type: 'velocity_check',
    label: 'Velocity Check',
    category: 'condition' as NodeCategory,
    description: 'Detect abnormal transaction burst and temporal anomalies.',
    icon: 'Zap',
  },
  {
    type: 'geo_risk',
    label: 'Geo Risk Analysis',
    category: 'condition' as NodeCategory,
    description: 'Evaluate corridor and geolocation mismatch risk.',
    icon: 'MapPin',
  },
  {
    type: 'tx_threshold',
    label: 'Transaction Threshold',
    category: 'condition' as NodeCategory,
    description: 'Branch logic when transaction amount crosses configured threshold.',
    icon: 'AlertTriangle',
  },
  {
    type: 'risk_aggregator',
    label: 'Risk Score Aggregator',
    category: 'condition' as NodeCategory,
    description: 'Aggregate rule and signal scores into final risk vector.',
    icon: 'GitBranch',
  },
  {
    type: 'ai_fraud_detection',
    label: 'AI Fraud Detection',
    category: 'condition' as NodeCategory,
    description: 'Run ML-assisted fraud score enrichment and confidence weighting.',
    icon: 'Shield',
  },
  {
    type: 'number_verify',
    label: 'Number Verification',
    category: 'telecom_signal' as NodeCategory,
    camaraApi: 'number_verify' as CamaraAPI,
    description: 'Verify the ownership of the provided phone number.',
    icon: 'Phone',
  },
  {
    type: 'kyc_match',
    label: 'KYC Match',
    category: 'telecom_signal' as NodeCategory,
    camaraApi: 'kyc_match' as CamaraAPI,
    description: 'Match provided user data against carrier KYC records.',
    icon: 'UserCheck',
  },
  {
    type: 'location_verify',
    label: 'Location Verify',
    category: 'telecom_signal' as NodeCategory,
    camaraApi: 'location_verify' as CamaraAPI,
    description: 'Compare transaction location with network presence.',
    icon: 'MapPin',
  },
  {
    type: 'roaming_status',
    label: 'Roaming Status',
    category: 'telecom_signal' as NodeCategory,
    camaraApi: 'roaming_status' as CamaraAPI,
    description: 'Check if the device is currently roaming internationally.',
    icon: 'Globe',
  },
  {
    type: 'condition',
    label: 'Condition Branch',
    category: 'condition' as NodeCategory,
    description: 'Route flow based on specific criteria.',
    icon: 'GitBranch',
  },
  {
    type: 'allow',
    label: 'Allow Transaction',
    category: 'decision' as NodeCategory,
    decisionType: 'ALLOW',
    description: 'Approve the transaction and proceed.',
    icon: 'CheckCircle',
  },
  {
    type: 'verify',
    label: 'Step-Up Authentication',
    category: 'decision' as NodeCategory,
    decisionType: 'VERIFY',
    description: 'Require additional authentication (OTP/MFA).',
    icon: 'AlertTriangle',
  },
  {
    type: 'webhook_trigger',
    label: 'Webhook Trigger',
    category: 'decision' as NodeCategory,
    decisionType: 'VERIFY',
    description: 'Notify external anti-fraud, SIEM, or SOC systems.',
    icon: 'Globe',
  },
  {
    type: 'session_restriction',
    label: 'Session Restriction',
    category: 'decision' as NodeCategory,
    decisionType: 'BLOCK',
    description: 'Temporarily restrict account or active user session.',
    icon: 'XCircle',
  },
  {
    type: 'block',
    label: 'Block Transaction',
    category: 'decision' as NodeCategory,
    decisionType: 'BLOCK',
    description: 'Reject the transaction immediately.',
    icon: 'XCircle',
  },
];
